### ISSUE TITLE
stats panel histograms slow to render or don't render 

### ISSUE THREAD

**Issue by ericberlow** [ericberlow/openmappr#4] opened 2018-07-18 15:44 UTC
open this project http://openmappr.swall.org/projects/5b4f5cbddedeac0013545615  
immediately open stats panel (click 'stats' button) 
scroll quickly to the bottom attributes - they are slow to load and the last ones often (not always) look like this:  https://cl.ly/3v2o0J222s3h

**Comment by mandeepm91** [comment] 2018-07-19 15:46
@ericberlow I am unable to reproduce this issue. Not sure if it was a temporary one? I tried it many times but wasn't able to produce the outcome that you've shown in the screenshot. It is rendering fine all the time. I will try it on a different computer with low end config because it is not a server side issue so could be related to the client pc config. Not sure though

**Comment by ericberlow** [comment] 2018-07-19 21:37
Thanks @mandeepm91 - I'll keep an eye on it and see if I can reproduce it and will let you know.

**Comment by ericberlow** [comment] 2018-07-20 13:44
@mandeepm91 - a version of this just happened now and i noticed these errors in the console:  https://cl.ly/0O1G183u1I3X 
project: http://openmappr.swall.org/projects/5b4f5cbddedeac0013545615

**Comment by ericberlow** [comment] 2018-07-20 13:47
note that after refreshing the browser everything rendered fine - 
https://cl.ly/3v300g1v0l3M

**Comment by mandeepm91** [comment] 2018-07-23 21:12
@ericberlow I was able to reproduce the issue where the attributes keep on loading but never get loaded. The problem is due to certain parts of the code executing before the data gets fetched from backend while actually they should execute after the data is loaded. To reproduce this, one has to quickly click on the stats panel. And the project must have relatively large volume of data for this issue to occur. I didn't see the error messages in the console that you sent but I saw a lot of other error messages. Mainly because I was able to produce the issue of spinners loading endlessly but never encountered the error where graphs are messed up like you've shown in the screenshot. My suspicion is that solving one should probably solve the other as well. I have made good progress on this today and I should be able to fix this issue by tomorrow.

**Comment by ericberlow** [comment] 2018-07-24 13:12
awesome @mandeepm91  - nice work.  it seems like in the process maybe the 'lazy loading' is not working, but i prefer the current behavior anyway.  i'll try to upload a file with many attributes to see if it's a problem.  but otherwise looks good.

**Comment by mandeepm91** [comment] 2018-07-24 14:32
Thanks @ericberlow . Let me know how the testing goes with the file with lots of attributes. Regarding the lazy loading, it was more of a UI thing so it's not like it is going to affect the performance.

**Comment by ericberlow** [comment] 2018-07-28 16:09
hi @mandeepm91 - stats panel seems to work fine but just noticed this:
in the project all attributes load fine http://openmappr.org/projects/5b5c8a1cc302e30011dea168 
in the published map the last attribute is missing http://openmappr.org/play/TEDTalks10Yrs

also - 
* in the project, when you change attribute settings in the 'data modal' - it seems to take a really long time for the settings to save. the screen freezes for a bit before you can do anything else. 
* here is a large network (9K nodes) with many attributes for other testing http://openmappr.org/projects/5b59706ec302e30011de9f1b

**Comment by mandeepm91** [comment] 2018-07-29 11:38
Hi @ericberlow , I've pushed a fix for the same. Please check and let me know if you still face any issues. Also, I met with Bimal this week and explained him the issue. I got to understand that lazy loading, even though a front end optimization only, is useful for cases when the number of attributes is very large because in that case the webpage can become quite heavy and affect the scrolling. We could not find a simple solution to bring back those loading spinners for now without causing all the issues that we were facing earlier. If we can live withouth those spinners and lazy loading for now, I can spend some time on this after a month maybe once I get more comfortable with the code while working on other issues.

**Comment by ericberlow** [comment] 2018-07-29 13:51
thanks @mandeepm91 - this is great for now. most cases will not have alot of attributes (and I can easily manage that). the lazy loaders have always been problematic because they were often slow to load, even in small datasets. so i'm happier with this other constraint :)    Let's see if it becomes a high priority issue to fix later.  One quick question I have is - if a dataset has many attributes, but most are 'hidden' - is it still a problem? Or will the hidden attributes still make the webpage 'heavy'?

**Comment by mandeepm91** [comment] 2018-07-29 13:53
Hidden ones should not cause any issues since they won't be rendered

**Comment by ericberlow** [comment] 2018-07-29 13:55
perfect. then lack of lazy loading should not be a problem. the UI in general is not great for navigating a very long list of attributes, so it's better to encourage people to only show the subset that are most relevant for filtering etc.

**Comment by mandeepm91** [comment] 2018-07-29 13:56
Cool. let me know if you encounter any other issue. If all works fine then we can merge the PR

**Closed** 2018-09-04 00:08 UTC
